CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  payment_code VARCHAR(64) NOT NULL UNIQUE,
  user_id VARCHAR(64) NULL,
  plan_id VARCHAR(32) NOT NULL,
  plan_name VARCHAR(64) NOT NULL,
  expected_amount INT UNSIGNED NOT NULL,
  paid_amount INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('pending', 'paid', 'failed', 'expired', 'cancelled') NOT NULL DEFAULT 'pending',
  provider VARCHAR(32) NOT NULL DEFAULT 'vietqr',
  provider_transaction_id VARCHAR(128) NULL UNIQUE,
  transfer_content VARCHAR(128) NOT NULL UNIQUE,
  license_id BIGINT UNSIGNED NULL,
  issued_raw_key VARCHAR(64) NULL,
  payment_secret_token VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL,
  paid_at DATETIME NULL,
  expired_at DATETIME NOT NULL,
  INDEX idx_payments_status (status),
  INDEX idx_payments_code (payment_code),
  INDEX idx_payments_transfer_content (transfer_content),
  INDEX idx_payments_created_at (created_at),
  INDEX idx_payments_license_id (license_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
